Bioconductor lpsymphony fosscuda pkg config
bear-rsg/easybuild-easyconfigs pull request #290
Opened 2020-09-18 11:58 UTC by edmondac

Bioconductor and magma patches from 2019a

2020-09-18 15:52 UTC, branfosj commented on easybuild/easyconfigs/m/magma/magma-2.5.1-fosscuda-2019b.eb
> +    prebuildopts += 'CFLAGS="-mno-float128 -std=c++11" '
Should this be:
```
    prebuildopts += 'CFLAGS="-mno-float128 -std=c++11 $CFLAGS" '
```

2020-09-18 15:53 UTC, branfosj requested changes
I think we want that change. Not certain.

2020-09-20 18:29 UTC, edmondac commented on easybuild/easyconfigs/m/magma/magma-2.5.1-fosscuda-2019b.eb
> +    prebuildopts += 'CFLAGS="-mno-float128 -std=c++11" '
yup

2020-09-20 19:04 UTC, branfosj approved these changes

2020-09-20 19:04 UTC, merged