Amber20
bear-rsg/easybuild-easyconfigs pull request #467
Opened 2021-01-20 10:42 UTC by orbsmiv

For INC1033241 - `Amber-20.9-AmberTools-20.14-foss-2020a-Python-2.7.16.eb`

* [ ] Assigned to reviewer

Default:
* [ ] EL7-cascadelake
* [ ] EL7-haswell
* [ ] EL7.9-cascadelake
* [ ] EL7.9-haswell
* [ ] EL8-cascadelake
* [ ] EL8-haswell

Add these if requested:
* [ ] EL8-power9

2021-02-08 13:04 UTC, branfosj commented
closing / reopening to rerun the test

2021-02-08 13:11 UTC, branfosj requested changes

2021-02-08 13:11 UTC, branfosj commented on easybuild/easyconfigs/a/Amber/Amber-20.9-AmberTools-20.14/tell_amber_about_ppc64le.patch
> +Allow AmberTools to detect a ppc64le is and tell it what to do when it detects one
Patch is not used - so delete

2021-02-08 13:11 UTC, branfosj commented on easybuild/easyconfigs/a/Amber/Amber-20.9-AmberTools-20.14-fosscuda-2020a-Python-3.8.2.eb
> +# threshold-based strategy in the easyblock
```suggestion
# Different tests pass and fail when using different numbers of processes. The manual makes it clear that this is expected.
```

2021-02-08 13:11 UTC, branfosj commented on easybuild/easyconfigs/a/Amber/Amber-20.9-AmberTools-20.14-foss-2020a-Python-3.8.2.eb
> +# threshold-based strategy in the easyblock
```suggestion
# Different tests pass and fail when using different numbers of processes. The manual makes it clear that this is expected.
```

2021-02-08 22:13 UTC, orbsmiv commented on easybuild/easyconfigs/a/Amber/Amber-20.9-AmberTools-20.14/tell_amber_about_ppc64le.patch
> +Allow AmberTools to detect a ppc64le is and tell it what to do when it detects one
resolved in 716f7d9

2021-02-09 06:44 UTC, branfosj approved these changes

2021-02-09 09:14 UTC, merged