LAMMPS 29Oct20 foss and fosscuda
bear-rsg/easybuild-easyconfigs pull request #523
Opened 2021-03-08 19:31 UTC by afraz-ahmed

For INC1109825 & INC1112385.

Please also see https://github.com/bear-rsg/easybuild-easyblocks/pull/72

* [ ] Assigned to reviewer

`LAMMPS-29Oct2020-foss-2020a-Python-3.8.2-kokkos.eb`
* [ ] EL7-cascadelake
* [ ] EL7-haswell
* [ ] EL8-cascadelake
* [ ] EL8-haswell

`LAMMPS-29Oct2020-fosscuda-2020a-Python-3.8.2-kokkos.eb`
(Note for Haswell: gpu needs to be present for sanity check commands to work)
* [ ] EL7-haswell
* [ ] EL8-haswell
* [ ] EL8-power9

2021-03-08 19:48 UTC, branfosj requested changes
A hopefully minor change. The VTK addition on POWER will need to be tested to check it still builds.

2021-03-08 19:48 UTC, branfosj commented on easybuild/easyconfigs/l/LAMMPS/LAMMPS-29Oct2020-fosscuda-2020a-Python-3.8.2-kokkos.eb
> +    ('VTK', {'arch=x86_64': '8.2.0', 'arch=POWER': False}, local_python_versionsuffix),
```suggestion
    ('VTK', '8.2.0', local_python_versionsuffix),
```

I fixed VTK to build on POWER in #463, so we should be fine to use it as a dep here.

2021-03-08 19:48 UTC, branfosj commented on easybuild/easyconfigs/l/LAMMPS/LAMMPS-29Oct2020-fosscuda-2020a-Python-3.8.2-kokkos.eb
> +# VTK (listed below) will only be enabled if VTK is a dependency (I.e. on x86_64 only)
```suggestion
```

2021-03-09 12:02 UTC, afraz-ahmed commented
VTK built successfully on Power9, although I needed to change `$EASYBUILD_TMPDIR`.

2021-03-09 12:32 UTC, branfosj approved these changes

2021-03-09 13:02 UTC, merged