Add IPO 1.16.0 easyconfig
bear-rsg/easybuild-easyconfigs pull request #590
Opened 2021-05-13 14:35 UTC by rpep

For INC?????? - `IPO-1.16.0-foss-2020b.eb`

* [ ] Assigned to reviewers (usually everyone in apps team)

Default:
* [ ] EL8-cascadelake
* [ ] EL8-haswell

Add these if requested:
* [ ] EL8-power9
* [ ] Ubuntu20 VM

2021-05-13 14:53 UTC, edmondac commented on easybuild/easyconfigs/i/IPO/IPO-1.16.0-foss-2020b.eb
> +exts_list = [
```suggestion
exts_list = [
    ('rsm', '2.10.2', {
        'checksums': ['66446cfb4298f1b306be286d1f2cd8b7f68acc900d3cc0d9a054aa48e192091c'],
    }),
```

2021-05-13 14:53 UTC, edmondac commented on easybuild/easyconfigs/r/rsm/rsm-2.10.2-foss-2020b.eb
> +easyblock = 'Bundle'
You can delete this file (and include it as an ext in IPO, as per my suggested edit above)

2021-05-13 14:53 UTC, edmondac requested changes
Please merge together as per my suggestion

2021-05-13 14:55 UTC, edmondac commented on easybuild/easyconfigs/i/IPO/IPO-1.16.0-foss-2020b.eb
> +    ('rsm', '2.10.2'),
```suggestion
```

2021-05-14 13:16 UTC, branfosj approved these changes

2021-05-14 13:19 UTC, edmondac approved these changes
lgtm

2021-05-14 13:19 UTC, merged