Visdom_bundle
bear-rsg/easybuild-easyconfigs pull request #663
Opened 2021-07-18 20:27 UTC by gyear

For INC1144697 - `visdom-0.1.8.9-foss-2020b.eb, PyZMQ-22.1.0-foss-2020b.eb`

* [ ] Assigned to reviewers (usually everyone in apps team)

Default:
* [ ] EL8-cascadelake
* [ ] EL8-haswell

2021-07-18 21:46 UTC, afraz-ahmed commented on easybuild/easyconfigs/p/PyZMQ/PyZMQ-22.1.0-foss-2020b.eb
> +toolchain = {'name': 'foss', 'version': '2020b'}
```suggestion
toolchain = {'name': 'GCCcore', 'version': '10.2.0'}
```
Use `GCCcore` instead of `foss` as the latest upstream version uses `GCCcore`. You can then also use the GCCcore version of `PyZMQ` with the `fosscuda` version of `visdom`.

2021-07-18 21:51 UTC, afraz-ahmed commented on easybuild/easyconfigs/p/PyZMQ/PyZMQ-22.1.0-foss-2020b.eb
> +
```suggestion

builddependencies = [('binutils', '2.35')]

```
`GCCcore` toolchain will require `binutils` as a build dep.

2021-07-18 22:01 UTC, afraz-ahmed commented on easybuild/easyconfigs/v/visdom/visdom-0.1.8.9-foss-2020b.eb
> +    'https://www.tornadoweb.org/en/stable/': [PYPI_SOURCE],
```suggestion
```
These aren't needed.

2021-07-18 22:02 UTC, afraz-ahmed requested changes
Please see the suggested changes.

2021-07-18 22:11 UTC, afraz-ahmed commented on easybuild/easyconfigs/v/visdom/visdom-0.1.8.9-foss-2020b.eb
> +    }),
```suggestion
```
This usually comes at the end of the extensions list.

2021-07-18 22:13 UTC, afraz-ahmed requested changes

2021-07-18 22:13 UTC, afraz-ahmed commented on easybuild/easyconfigs/v/visdom/visdom-0.1.8.9-foss-2020b.eb
> +]
```suggestion
(name, version, {
         'checksums': ['c73ad23723c24a48156899f78dd76bd4538eba3edf9120b6c65a9528fa677126'],
    }),
]
```

2021-07-20 16:08 UTC, edmondac requested changes
Just those suggestions then we're good to go

2021-07-20 16:08 UTC, edmondac commented on easybuild/easyconfigs/p/PyZMQ/PyZMQ-22.1.0-GCCcore-10.2.0.eb
> +local_zmqversion = '4.3.3'
```suggestion
```

2021-07-20 16:08 UTC, edmondac commented on easybuild/easyconfigs/p/PyZMQ/PyZMQ-22.1.0-GCCcore-10.2.0.eb
> +    ('ZeroMQ', local_zmqversion),
```suggestion
    ('ZeroMQ', '4.3.3'),
```

2021-07-20 16:16 UTC, edmondac approved these changes
lgtm

2021-07-20 16:16 UTC, merged