ChIPseeker
bear-rsg/easybuild-easyconfigs pull request #788
Opened 2022-01-10 20:39 UTC by gyear

For INC1209490 - `ChIPseeker-1.30.3-foss-2021a-R-4.1.0.eb`

* [ ] Assigned to reviewers (usually everyone in apps team)

Default:
* [ ] EL8-cascadelake
* [ ] EL8-haswell
* [ ] EL8-icelake

2022-01-11 08:34 UTC, branfosj requested changes

2022-01-11 08:34 UTC, branfosj commented on easybuild/easyconfigs/c/ChIPseeker/ChIPseeker-1.30.3-foss-2021a-R-4.1.0.eb
> +version = '1.30.3'
https://bioconductor.org/packages/3.13/bioc/html/ChIPseeker.html for the version of ChIPseeker from Bioconductor 3.13.

So this should be `version = 'version = '1.30.3''`

2022-01-11 08:34 UTC, branfosj commented on easybuild/easyconfigs/c/ChIPseeker/ChIPseeker-1.30.3-foss-2021a-R-4.1.0.eb
> +        'https://bioconductor.org/packages/release/bioc/src/contrib/',  # my addition
```suggestion
```

That will get packages from Bioconductor 3.14, which can cause odd issues. Use https://bioconductor.org/packages/3.13/BiocViews.html#___Software as a starting point.

I've suggested the ones below that I think need to change due to this - the others are from CRAN. Checksums will need updating and then test build this to check that the package dependencies are fine.

2022-01-11 08:34 UTC, branfosj commented on easybuild/easyconfigs/c/ChIPseeker/ChIPseeker-1.30.3-foss-2021a-R-4.1.0.eb
> +    ('GOSemSim', '2.20.0', {
```suggestion
    ('GOSemSim', '2.18.1', {
```

2022-01-11 08:34 UTC, branfosj commented on easybuild/easyconfigs/c/ChIPseeker/ChIPseeker-1.30.3-foss-2021a-R-4.1.0.eb
> +    ('DOSE', '3.20.1', {
```suggestion
    ('DOSE', '3.18.3', {
```

2022-01-11 08:34 UTC, branfosj commented on easybuild/easyconfigs/c/ChIPseeker/ChIPseeker-1.30.3-foss-2021a-R-4.1.0.eb
> +    ('treeio', '1.18.1', {
```suggestion
    ('treeio', '1.16.2', {
```

2022-01-11 08:34 UTC, branfosj commented on easybuild/easyconfigs/c/ChIPseeker/ChIPseeker-1.30.3-foss-2021a-R-4.1.0.eb
> +    ('ggtree', '3.2.1', {
```suggestion
    ('ggtree', '3.0.4', {
```

2022-01-11 08:34 UTC, branfosj commented on easybuild/easyconfigs/c/ChIPseeker/ChIPseeker-1.30.3-foss-2021a-R-4.1.0.eb
> +    ('enrichplot', '1.14.1', {
```suggestion
    ('enrichplot', '1.12.3', {
```

2022-01-12 09:55 UTC, branfosj commented on easybuild/easyconfigs/c/ChIPseeker/ChIPseeker-1.30.3-foss-2021a-R-4.1.0.eb
> +version = '1.30.3'
Update comment above, which will hopefully make more sense

2022-01-12 09:55 UTC, edmondac commented on easybuild/easyconfigs/c/ChIPseeker/ChIPseeker-1.30.3-foss-2021a-R-4.1.0.eb
> +version = '1.30.3'
This will need the filename changing too

2022-01-13 11:22 UTC, branfosj approved these changes

2022-01-13 11:34 UTC, merged