Armadillo-10.7.4
bear-rsg/easybuild-easyconfigs pull request #789
Opened 2022-01-10 22:36 UTC by sihart25

- [ ] Assigned to reviewers (usually everyone in apps team)

Default:
- [ ] EL8-cascadelake
- [ ] EL8-haswell
- [ ] EL8-icelake

Add these if requested: 

- [ ] Ubuntu20 VM

2022-01-11 08:20 UTC, branfosj requested changes
That should be sufficient for the dependencies to be found. Can you test build that?

2022-01-11 08:20 UTC, branfosj commented on easybuild/easyconfigs/a/Armadillo/Armadillo-10.7.4-foss-2021a.eb
> +    ('arpack-ng', '3.8.0', '', ('foss', '2021a')),
```suggestion
    ('Boost', '1.76.0'),
    ('arpack-ng', '3.8.0'),
```

2022-01-18 18:54 UTC, sihart25 commented
Tested after Requested changes

2022-01-19 13:56 UTC, branfosj approved these changes

2022-01-19 15:42 UTC, merged