WRF with hydro for combined construction
bear-rsg/easybuild-easyconfigs pull request #934
Opened 2022-08-05 14:30 UTC by gyear

For INC1215665 - `WRF-4.2.2-foss-2020b-combined.eb`

* [ ] Assigned to reviewers (usually everyone in apps team)

Default:
* [ ] EL8-cascadelake
* [ ] EL8-haswell

2022-08-15 09:29 UTC, gyear commented
Build first updated easyblock
https://github.com/bear-rsg/easybuild-easyblocks/pull/112

2022-08-15 09:38 UTC, branfosj requested changes

2022-08-15 09:38 UTC, branfosj commented on easybuild/easyconfigs/w/WRF/WRF-4.2.2-foss-2020b-combined.eb
> +preconfigopts += "setenv HYDRO_D 1"
Are these needed in addition to the change in the easyblock?

2022-08-15 09:38 UTC, branfosj commented on easybuild/easyconfigs/w/WRF/WRF-4.2.2-foss-2020b-combined.eb
> +# Combined WRF location
Please add a comment here as to explain how this `-combined` version `.tar.gz` was created.

2022-08-24 11:59 UTC, branfosj approved these changes

2022-08-24 12:04 UTC, merged